# Generated by Django 5.0.4 on 2024-05-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_categorie_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.categorie'),
        ),
    ]
