# Generated by Django 5.0.4 on 2024-06-01 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_evenement_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='user',
        ),
        migrations.AddField(
            model_name='evenement',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='evenements', to=settings.AUTH_USER_MODEL),
        ),
    ]
